name: cinemapedia_2023
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.1.1
  flutter_dotenv: ^5.1.0
  dio: ^5.3.2
  flutter_riverpod: ^2.4.0
  card_swiper: ^3.0.1
  animate_do: ^3.1.2
  intl: ^0.18.1

dev_dependencies:
 ## flutter_test:
 ##   sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
  #   - images/a_dot_burr.jpeg
